version: 2
jobs:
  one:
    branches:
      - development
    docker:
      - image: circleci/gradle:jdk11
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    branches:
      - development
    docker:
      - image: circleci/gradle:jdk11
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
